service: aws-coldstart-java

provider:
  name: aws
  runtime: java8
  versionFunctions: false

package:
  artifact: target/hello-dev.jar

functions:
  memory-128:
    handler: com.swell.Handler
    memorySize: 128

  memory-256:
    handler: com.swell.Handler
    memorySize: 256

  memory-512:
    handler: com.swell.Handler
    memorySize: 512

  memory-1024:
    handler: com.swell.Handler
    memorySize: 1024

  memory-1536:
    handler: com.swell.Handler
    memorySize: 1536